version: '1.0'

services:
  mongodb:
    image: mongo:latest
    container_name: code_tl_musicbrainz
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: